name: test
on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and cache Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install packages
        run: npm ci -w packages/worker
      - name: Run test
        run: npm run test -w packages/worker -- --bail --maxWorkers=100% --watchAll=false --coverage